package com.atguigu.mybatis.pojo;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.id
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.name
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.gender
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.password
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.email
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.telephone
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.address
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.portrait_path
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    private String portraitPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.id
     *
     * @return the value of tb_admin.id
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin.id
     *
     * @param id the value for tb_admin.id
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.name
     *
     * @return the value of tb_admin.name
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin.name
     *
     * @param name the value for tb_admin.name
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.gender
     *
     * @return the value of tb_admin.gender
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin.gender
     *
     * @param gender the value for tb_admin.gender
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.password
     *
     * @return the value of tb_admin.password
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin.password
     *
     * @param password the value for tb_admin.password
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.email
     *
     * @return the value of tb_admin.email
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin.email
     *
     * @param email the value for tb_admin.email
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.telephone
     *
     * @return the value of tb_admin.telephone
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin.telephone
     *
     * @param telephone the value for tb_admin.telephone
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.address
     *
     * @return the value of tb_admin.address
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin.address
     *
     * @param address the value for tb_admin.address
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.portrait_path
     *
     * @return the value of tb_admin.portrait_path
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    public String getPortraitPath() {
        return portraitPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin.portrait_path
     *
     * @param portraitPath the value for tb_admin.portrait_path
     *
     * @mbggenerated Fri Jul 01 15:37:01 CST 2022
     */
    public void setPortraitPath(String portraitPath) {
        this.portraitPath = portraitPath == null ? null : portraitPath.trim();
    }
}